handler: aime
dataset_path: AI-MO/aimo-validation-aime
dataset_split: train
question_key: problem
answer_key: answer
templating_parameters:
  regular_template:  "Return your final response within \\boxed{{}}. {prompt}"
  sky_template: "{prompt}\nReturn your final response within \\boxed{{}}" 